/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnchorBar: typeof import('./src/components/anchorBar.vue')['default']
    AnchorBar2: typeof import('./src/components/anchorBar2.vue')['default']
    AnchorBar3: typeof import('./src/components/anchorBar3.vue')['default']
    AnchorBar4: typeof import('./src/components/anchorBar4.vue')['default']
    BackTop: typeof import('./src/components/backTop.vue')['default']
    BookMark: typeof import('./src/components/bookMark/bookMark.vue')['default']
    BookMarkList: typeof import('./src/components/bookMark/bookMarkList.vue')['default']
    CardPic: typeof import('./src/components/cardPic.vue')['default']
    DiyCard: typeof import('./src/components/diyCard.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IIon:sync': typeof import('~icons/ion/sync')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPic: typeof import('./src/components/scrollPic.vue')['default']
    TopIcon: typeof import('./src/components/topIcon.vue')['default']
  }
}
